/**
 * Prognostics as a Service API
 * The PaaS REST API exposes the GSAP prognostics architecture as an internet accessible service. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: christopher.a.teubert@nasa.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.V1dataData;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class DataFrame {
  
  @SerializedName("is_future")
  private Boolean isFuture = null;
  @SerializedName("data")
  private List<V1dataData> data = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getIsFuture() {
    return isFuture;
  }
  public void setIsFuture(Boolean isFuture) {
    this.isFuture = isFuture;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<V1dataData> getData() {
    return data;
  }
  public void setData(List<V1dataData> data) {
    this.data = data;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataFrame dataFrame = (DataFrame) o;
    return (this.isFuture == null ? dataFrame.isFuture == null : this.isFuture.equals(dataFrame.isFuture)) &&
        (this.data == null ? dataFrame.data == null : this.data.equals(dataFrame.data));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.isFuture == null ? 0: this.isFuture.hashCode());
    result = 31 * result + (this.data == null ? 0: this.data.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataFrame {\n");
    
    sb.append("  isFuture: ").append(isFuture).append("\n");
    sb.append("  data: ").append(data).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
