/**
 * Prognostics as a Service API
 * The PaaS REST API exposes the GSAP prognostics architecture as an internet accessible service. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: christopher.a.teubert@nasa.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.InlineResponse2002Vehicles;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse2003 {
  
  @SerializedName("id")
  private Long id = null;
  @SerializedName("owner_id")
  private Long ownerId = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("systems")
  private List<InlineResponse2002Vehicles> systems = null;
  @SerializedName("trajectory_ids")
  private List<Long> trajectoryIds = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }
  public void setId(Long id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getOwnerId() {
    return ownerId;
  }
  public void setOwnerId(Long ownerId) {
    this.ownerId = ownerId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<InlineResponse2002Vehicles> getSystems() {
    return systems;
  }
  public void setSystems(List<InlineResponse2002Vehicles> systems) {
    this.systems = systems;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Long> getTrajectoryIds() {
    return trajectoryIds;
  }
  public void setTrajectoryIds(List<Long> trajectoryIds) {
    this.trajectoryIds = trajectoryIds;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2003 inlineResponse2003 = (InlineResponse2003) o;
    return (this.id == null ? inlineResponse2003.id == null : this.id.equals(inlineResponse2003.id)) &&
        (this.ownerId == null ? inlineResponse2003.ownerId == null : this.ownerId.equals(inlineResponse2003.ownerId)) &&
        (this.name == null ? inlineResponse2003.name == null : this.name.equals(inlineResponse2003.name)) &&
        (this.systems == null ? inlineResponse2003.systems == null : this.systems.equals(inlineResponse2003.systems)) &&
        (this.trajectoryIds == null ? inlineResponse2003.trajectoryIds == null : this.trajectoryIds.equals(inlineResponse2003.trajectoryIds));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.ownerId == null ? 0: this.ownerId.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.systems == null ? 0: this.systems.hashCode());
    result = 31 * result + (this.trajectoryIds == null ? 0: this.trajectoryIds.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2003 {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  ownerId: ").append(ownerId).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  systems: ").append(systems).append("\n");
    sb.append("  trajectoryIds: ").append(trajectoryIds).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
