/**
 * Prognostics as a Service API
 * The PaaS REST API exposes the GSAP prognostics architecture as an internet accessible service. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: christopher.a.teubert@nasa.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse2006 {
  
  @SerializedName("id")
  private Long id = null;
  @SerializedName("owner_id")
  private Long ownerId = null;
  @SerializedName("vehicle_id")
  private Long vehicleId = null;
  @SerializedName("status")
  private String status = null;
  @SerializedName("start_time")
  private Long startTime = null;
  @SerializedName("last_message")
  private Long lastMessage = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }
  public void setId(Long id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getOwnerId() {
    return ownerId;
  }
  public void setOwnerId(Long ownerId) {
    this.ownerId = ownerId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getVehicleId() {
    return vehicleId;
  }
  public void setVehicleId(Long vehicleId) {
    this.vehicleId = vehicleId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }
  public void setStatus(String status) {
    this.status = status;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getStartTime() {
    return startTime;
  }
  public void setStartTime(Long startTime) {
    this.startTime = startTime;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getLastMessage() {
    return lastMessage;
  }
  public void setLastMessage(Long lastMessage) {
    this.lastMessage = lastMessage;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2006 inlineResponse2006 = (InlineResponse2006) o;
    return (this.id == null ? inlineResponse2006.id == null : this.id.equals(inlineResponse2006.id)) &&
        (this.ownerId == null ? inlineResponse2006.ownerId == null : this.ownerId.equals(inlineResponse2006.ownerId)) &&
        (this.vehicleId == null ? inlineResponse2006.vehicleId == null : this.vehicleId.equals(inlineResponse2006.vehicleId)) &&
        (this.status == null ? inlineResponse2006.status == null : this.status.equals(inlineResponse2006.status)) &&
        (this.startTime == null ? inlineResponse2006.startTime == null : this.startTime.equals(inlineResponse2006.startTime)) &&
        (this.lastMessage == null ? inlineResponse2006.lastMessage == null : this.lastMessage.equals(inlineResponse2006.lastMessage));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.ownerId == null ? 0: this.ownerId.hashCode());
    result = 31 * result + (this.vehicleId == null ? 0: this.vehicleId.hashCode());
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    result = 31 * result + (this.startTime == null ? 0: this.startTime.hashCode());
    result = 31 * result + (this.lastMessage == null ? 0: this.lastMessage.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2006 {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  ownerId: ").append(ownerId).append("\n");
    sb.append("  vehicleId: ").append(vehicleId).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("  startTime: ").append(startTime).append("\n");
    sb.append("  lastMessage: ").append(lastMessage).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
