/**
 * Prognostics as a Service API
 * The PaaS REST API exposes the GSAP prognostics architecture as an internet accessible service. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: christopher.a.teubert@nasa.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.InlineResponse2002Vehicles;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class User {
  
  @SerializedName("id")
  private Long id = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("vehicles")
  private List<InlineResponse2002Vehicles> vehicles = null;
  @SerializedName("components")
  private List<InlineResponse2002Vehicles> components = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }
  public void setId(Long id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<InlineResponse2002Vehicles> getVehicles() {
    return vehicles;
  }
  public void setVehicles(List<InlineResponse2002Vehicles> vehicles) {
    this.vehicles = vehicles;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<InlineResponse2002Vehicles> getComponents() {
    return components;
  }
  public void setComponents(List<InlineResponse2002Vehicles> components) {
    this.components = components;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    User user = (User) o;
    return (this.id == null ? user.id == null : this.id.equals(user.id)) &&
        (this.name == null ? user.name == null : this.name.equals(user.name)) &&
        (this.vehicles == null ? user.vehicles == null : this.vehicles.equals(user.vehicles)) &&
        (this.components == null ? user.components == null : this.components.equals(user.components));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.vehicles == null ? 0: this.vehicles.hashCode());
    result = 31 * result + (this.components == null ? 0: this.components.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class User {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  vehicles: ").append(vehicles).append("\n");
    sb.append("  components: ").append(components).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
