/**
 * Prognostics as a Service API
 * The PaaS REST API exposes the GSAP prognostics architecture as an internet accessible service. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: christopher.a.teubert@nasa.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class V1dataData {
  
  @SerializedName("timestamp")
  private Long timestamp = null;
  @SerializedName("system_id")
  private Long systemId = null;
  @SerializedName("tag")
  private String tag = null;
  @SerializedName("value")
  private Double value = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getTimestamp() {
    return timestamp;
  }
  public void setTimestamp(Long timestamp) {
    this.timestamp = timestamp;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getSystemId() {
    return systemId;
  }
  public void setSystemId(Long systemId) {
    this.systemId = systemId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTag() {
    return tag;
  }
  public void setTag(String tag) {
    this.tag = tag;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getValue() {
    return value;
  }
  public void setValue(Double value) {
    this.value = value;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1dataData v1dataData = (V1dataData) o;
    return (this.timestamp == null ? v1dataData.timestamp == null : this.timestamp.equals(v1dataData.timestamp)) &&
        (this.systemId == null ? v1dataData.systemId == null : this.systemId.equals(v1dataData.systemId)) &&
        (this.tag == null ? v1dataData.tag == null : this.tag.equals(v1dataData.tag)) &&
        (this.value == null ? v1dataData.value == null : this.value.equals(v1dataData.value));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.timestamp == null ? 0: this.timestamp.hashCode());
    result = 31 * result + (this.systemId == null ? 0: this.systemId.hashCode());
    result = 31 * result + (this.tag == null ? 0: this.tag.hashCode());
    result = 31 * result + (this.value == null ? 0: this.value.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1dataData {\n");
    
    sb.append("  timestamp: ").append(timestamp).append("\n");
    sb.append("  systemId: ").append(systemId).append("\n");
    sb.append("  tag: ").append(tag).append("\n");
    sb.append("  value: ").append(value).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
